### ISSUE TITLE
Python3 compiled raised an error

### ISSUE THREAD

**Issue by johanesn** [vmayoral/basic_reinforcement_learning#3]

**Comment by johanesn** [comment]
I try to compile with python3 and I got error like this:

Traceback (most recent call last):
  File "DQNMountainCarDiscrete.py", line 351, in <module>
    deepQ.learnOnMiniBatch(minibatch_size, False)
  File "DQNMountainCarDiscrete.py", line 265, in learnOnMiniBatch
    miniBatch = self.memory.getMiniBatch(miniBatchSize)
  File "DQNMountainCarDiscrete.py", line 44, in getMiniBatch
    indices = random.sample(np.arange(len(self.states)), min(size,len(self.states))) 
  File "/usr/lib/python3.5/random.py", line 311, in sample
    raise TypeError("Population must be a sequence or set.  For dicts, use list(d).")
TypeError: Population must be a sequence or set.  For dicts, use list(d).

Please, can anybody help me?

**Comment by vmayoral** [comment]
@johanesn, if you need support provide a proper description of the issue you're experiencing including the tutorial you are trying to reproduce and your particular environment.

Closing it for now. Feel free to launch another issue with appropriate description and title.
